name: CI

# Controls when the workflow will run
# For more information see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv and Poetry (for dev dependencies)
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          pip install poetry

      - name: Install Project Dependencies with uv
        run: |
          uv vcs //.
          uv pip install --frozen -r requirements.txt
          uv pip install --frozen -r requirements_dev.txt

      - name: Lint and Format with Ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Test with Pytest
        run: |
          pytest
